# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kswiftsample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kswiftsample
  pod 'mpp_library', :path => '../mpp-library'
  pod 'KSwift', :path => '../mpp-library'
end
